version: '3'
services:
  node:
    build:
      context: .
      dockerfile: ./docker/Dockerfile.hardhat
    env_file:
      - .env
    ports:
      - 8545:8545
    volumes:
      - ./contracts:/app/contracts:z
      - ./scripts:/app/scripts:z
      - ./artifacts:/app/artifacts:z

  ui:
    build:
      context: .
      dockerfile: ./docker/Dockerfile.ui
    env_file:
      - .env
    ports:
      - 3000:3000
    volumes:
      - ./src:/app/src:z
